project:
  type: website

website:
  title: "mZaiam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Deep Learning
        menu:
          - href: deep_learning/mlp.qmd
            text: Neural Networks (NNs)

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true