project:
  type: website

crossref:
  fig-prefix: "Fig."
  eq-prefix: "Eq."

website:
  bread-crumbs: true 
  page-navigation: true

  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        file: index.qmd
        
      - section: "Machine Learning"
        file: machine_learning/index.qmd 
        contents:
          - section: "Pipeline"
            file: machine_learning/pipeline/index.qmd
            contents:
              - text: "Pre-Processing"
                file: machine_learning/pipeline/pre_processing/pre_processing.qmd
              - text: "Model Selection"
                file: machine_learning/pipeline/model_selection/model_selection.qmd
              - text: "Model Evaluation"
                file: machine_learning/pipeline/model_evaluation/model_evaluation.qmd
          - section: "Supervised Learning"
            file: machine_learning/supervised_learning/index.qmd
            contents:
              - text: "Linear Models"
                file: machine_learning/supervised_learning/linear_models/linear_models.qmd
           
      - section: "Deep Learning"
        file: deep_learning/index.qmd
        contents:
          - text: "Multilayer Perceptron"
            file: deep_learning/mlp/mlp.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true