---
title: "Graph Neural Networks"
bibliography: ../../../references.bib
---

graph is a set $\mathcal G = (\mathcal V, \mathcal E)$, with vertices and edges. directional edge is denoted $(u, v) \in \mathcal E$. could be represented using the adjacency matrix $\boldsymbol A \in \mathbb R^{|\mathcal V| \times |\mathcal E|}$. directed/undirected. weighted/not weighted. 

multi-relational graphs have different edge types $\boldsymbol A \in \mathbb R^{|\mathcal V| \times |\mathcal R| \times |\mathcal E|}$, with a set of relations. heterogeneous and multiplex graphs are examples.

graphs can have features $\mathcal X \in \mathbb R^{|\mathcal V| \times m}$.

tasks include: node classification, relation prediction, community detection (clustering), graph datasets tasks

node degree $d_u = \sum_{v \in \mathcal V} \boldsymbol A[u, v]$
node eigenvector centrality $\lambda \boldsymbol e = \boldsymbol A \boldsymbol e$. tells the likelihood of visiting a node into an infinite random walk
clustering coeef