---
title: "Denoising Diffusion Probabilistic Models (DDPM)"
bibliography: ../../references.bib
---

Following the [Score Matching with Langevin Dynamics (SMLD)](../smld.qmd), Denoising Diffusion Probabilistic Models (DDPMs) [@dm:ddpm] formulated a Diffusion Models (DMs) as two separate processes. The forward, or diffusion process was defined as a fixed Markov chain that increasingly adds noise to the original data $\boldsymbol{x}_0$, being described as:
$$
q(\boldsymbol{x}_{1:T}\mid \boldsymbol{x}_0) = \prod_{t=1}^T q(\boldsymbol{x}_t\mid \boldsymbol{x}_{t-1}),
$$ {#eq-1}
where $T\in \mathbb N$ is the number of states in the chain. Each transition in this process can be expressed as:
$$
q(\boldsymbol{x}_t\mid \boldsymbol{x}_{t-1}) = \mathcal N\left(\boldsymbol{x}_t\mid \sqrt{1-\beta_t}\boldsymbol{x}_{t-1}, \beta_t\boldsymbol{I}\right),
$$ {#eq-2}
where $\{\beta_i\}_{i=1}^T$ is a variance schedule. The diffusion process admits sampling any step in the chain directly from the original sample, with the following:
$$
\boldsymbol x_t = \sqrt{\overline{\alpha}_t}\boldsymbol x_0 + \sqrt{1 - \overline{\alpha}_t} \boldsymbol \epsilon,
$$ {#eq-3}
where $\alpha_t = 1 - \beta_t$, $\overline{\alpha}_t = \prod_{s=1}^t \alpha_s$ and $\boldsymbol{\epsilon}\sim \mathcal N(\boldsymbol{\epsilon}\mid\boldsymbol{0}, \boldsymbol{I})$. 

The reverse process is a Markov chain where the Gaussian transitions are learned via a parametrized Neural Network (NN). Starting $\boldsymbol{x}_T\sim\mathcal N(\boldsymbol{x}_T\mid \boldsymbol{0}, \boldsymbol{I})$, the NN parametrized by $\boldsymbol{\theta}$ approximates the following chain:
$$
p_{\boldsymbol{\theta}}\left(\boldsymbol{x}_{0:T}\right) = p(\boldsymbol x_T) \prod_{t=1}^T p_{\boldsymbol \theta}(\boldsymbol x_{t-1}\mid \boldsymbol x_t).
$$ {#eq-4}
Each transition step is expressed as:
$$
p_{\boldsymbol{\theta}}(\boldsymbol{x}_{t-1} \mid \boldsymbol{x}_{t}) = \mathcal N\left(\boldsymbol{x}_{t-1}\mid  {\boldsymbol\mu}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t), {\boldsymbol\Sigma}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t)\right).
$$ {#eq-5}
That is, the DM learns the mean ${\boldsymbol\mu}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t)$ and variance ${\boldsymbol\Sigma}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t)$ to reverse the noise from $\boldsymbol{x}_{t}$ to $\boldsymbol{x}_{t-1}$. To achieve this, the model is conditioned on the time step $t$.

The NN is trained to minimize the negative log likelihood of the data. Making some algebraic steps:
$$
\begin{aligned}
\mathcal L(\boldsymbol{\theta}) &= \mathbb E\left[ -\log p_{\boldsymbol{\theta}} (\boldsymbol{x}_0)\right] \leq \mathbb E_q\left[- \log\frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{0:T})}{q(\boldsymbol{x}_{1:T} \mid \boldsymbol{x}_0)}\right] \\
&= \mathbb E_q\left[- \log p(\boldsymbol{x}_T) - \sum_{t\geq 1} \log\frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{t-1} \mid \boldsymbol{x}_t)}{q(\boldsymbol{x}_{t} \mid \boldsymbol{x}_{t-1})}\right] \\
&= \mathbb E_q\left[- \log p(\boldsymbol{x}_T) - \log \frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{0} \mid \boldsymbol{x}_1)}{q(\boldsymbol{x}_{1} \mid \boldsymbol{x}_{0})} - \sum_{t> 1}\log \frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{t-1} \mid \boldsymbol{x}_t)}{q(\boldsymbol{x}_{t} \mid \boldsymbol{x}_{t-1})}\right].
\end{aligned}
$$ {#eq-6}
Applying Bayes' Theorem to the forward Markov chain:
$$
\begin{aligned}
    &= \mathbb E_q\left[- \log p(\boldsymbol{x}_T) - \log \frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{0} \mid \boldsymbol{x}_1)}{q(\boldsymbol{x}_{1} \mid \boldsymbol{x}_{0})} - \sum_{t> 1}  \log  \frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{t-1} \mid \boldsymbol{x}_t)q(\boldsymbol x_{t-1} \mid \boldsymbol{x}_0)}{q(\boldsymbol{x}_{t-1} \mid \boldsymbol{x}_{t}, \boldsymbol{x}_0) q(\boldsymbol{x}_{t} \mid \boldsymbol{x}_{0})} \right]  \\
    &= \mathbb E_q\left[- \log \frac{p(\boldsymbol{x}_T)}{q(\boldsymbol{x}_T \mid \boldsymbol{x}_0)} - \log p_{\boldsymbol{\theta}} (\boldsymbol x_{0} \mid \boldsymbol{x}_1)- \sum_{t> 1}  \log  \frac{p_{\boldsymbol{\theta}} (\boldsymbol x_{t-1} \mid \boldsymbol{x}_t)}{q(\boldsymbol{x}_{t-1} \mid \boldsymbol{x}_{t}, \boldsymbol{x}_0)}\right] \\
    &= \mathbb E_q\bigg[ \underbrace{D_{\text{KL}} \bigg(q(\boldsymbol{x}_T \mid \boldsymbol{x}_0) \parallel p(\boldsymbol{x}_T) \bigg)}_{\mathcal L_T} \underbrace{- \log p_{\boldsymbol{\theta}} (\boldsymbol x_{0} \mid \boldsymbol{x}_1)}_{\mathcal L_0}  \\
    &\qquad \qquad \qquad + \sum_{t> 1} \underbrace{D_{\text{KL}} \bigg(q(\boldsymbol{x}_{t-1} \mid \boldsymbol{x}_{t}, \boldsymbol{x}_0) \parallel p_{\boldsymbol{\theta}}(\boldsymbol{x}_{t-1} \mid \boldsymbol{x} _t) \bigg)}_{\mathcal L_{t-1}}\bigg],
\end{aligned}
$$ {#eq-7}
where $D_{\text{KL}}$ is the Kullback-Leibler divergence. Note that by fixing the forward process, the term $\mathcal L_T$ does not depend on $\boldsymbol{\theta}$ and can therefore be ignored. For the $\mathcal L_{1:T-1}$ terms, the variance of the NN is fixed to ${\boldsymbol\Sigma}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t) = \sigma_t^2\boldsymbol{I} = \beta_t \boldsymbol{I}$. 

With the variance fixed, the KL divergence in the $\mathcal{L}_{t-1}$ terms compares two Gaussian distributions. This simplifies to the mean squared  error between their means. The posterior $q(\boldsymbol{x}_{t-1} \mid \boldsymbol{x}_t, \boldsymbol{x}_0)$ is also a Gaussian, therefore, minimizing $\mathcal{L}_{t-1}$ is equivalent to minimizing the difference between the true posterior mean $\tilde{\boldsymbol{\mu}}_t$ and the NN's predicted mean $\boldsymbol{\mu}_{\boldsymbol{\theta}}$:
$$
\mathcal L_{t-1} = \mathbb E_q \left[ \frac{1}{2\sigma_t^2} \left\| \tilde{\boldsymbol{\mu}}_t(\boldsymbol{x}_t, \boldsymbol{x}_0) - \boldsymbol{\mu}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t) \right\|^2 \right] + C,
$$ {#eq-8}
where $C$ is a constant independent of $\boldsymbol{\theta}$. With some reparametrization tricks, it is possible to show that these terms can be expressed as:
$$
\mathcal L_{t-1} = \mathbb E_{\boldsymbol{x}_0, \boldsymbol{\epsilon}} \left[ \frac{\beta_t^2}{2\sigma_t^2 \alpha_t (1 - \overline{\alpha}_t)} \left\| \boldsymbol{\epsilon} - \boldsymbol{\epsilon}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t) \right\|^2 \right],
$$ {#eq-9}
where $\boldsymbol{\epsilon}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t)$ is the noise predicted by the NN. It was observed that ignoring the weighting term  lead to better results. This results in the final simplified objective function used to train DDPMs:
$$
\mathcal L(\boldsymbol{\theta}) = \mathbb E_{t, \boldsymbol{x}_0, \boldsymbol{\epsilon}} \left[ \left\| \boldsymbol{\epsilon} - \boldsymbol{\epsilon}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t) \right\|^2 \right].
$$ {#eq-10}

After training the NN $\boldsymbol{\epsilon}_{\boldsymbol{\theta}}$ to approximate the noise added to the data, the model can be used to generate new samples from the learned data distribution $p_{\boldsymbol{\theta}}(\boldsymbol{x}_0)$. The reverse process begins by sampling pure Gaussian noise $\boldsymbol{x}_T \sim \mathcal{N}(\boldsymbol{0}, \boldsymbol{I})$ and iteratively denoising it down to $t=0$. The iterative process is described by:
$$
\boldsymbol{x}_{t-1} = \frac{1}{\sqrt{\alpha_t}}\left(\boldsymbol{x}_t - \frac{\beta_t}{\sqrt{1-\overline{\alpha}_t}} \boldsymbol{\epsilon}_{\boldsymbol{\theta}}(\boldsymbol{x}_t, t)\right) + \sigma_t\boldsymbol{z},
$$ {#eq-11}
where $\boldsymbol{z} \sim \mathcal{N}(\boldsymbol{0}, \boldsymbol{I})$ for $t > 1$. At the final step when $t = 1$, $\boldsymbol{z} = \boldsymbol{0}$ is set to output the deterministic mean, as adding noise at the very end would degrade the final image.

### Code

{{< embed theoretical_foundation_assets/ddpm.ipynb >}}